# TCL File Generated by Component Editor 11.1sp1
# Mon Jan 30 20:37:15 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | DM9000A_IF "DM9000A_IF" v1.0
# | null 2012.01.30.20:37:15
# | 
# | 
# | D:/Home/User/Desktop/SOPC_Builder/Reference_Design/DE2_qsys/DM9000A/hdl/DM9000A_IF.v
# | 
# |    ./DM9000A_IF.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module DM9000A_IF
# | 
set_module_property NAME DM9000A_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME DM9000A_IF
set_module_property TOP_LEVEL_HDL_FILE DM9000A_IF.v
set_module_property TOP_LEVEL_HDL_MODULE DM9000A_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME DM9000A_IF
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file DM9000A_IF.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 2
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 40
set_interface_property avalon_slave_0 readWaitTime 40
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitStates 40
set_interface_property avalon_slave_0 writeWaitTime 40

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 oDATA readdata Output 16
add_interface_port avalon_slave_0 iCMD address Input 1
add_interface_port avalon_slave_0 iRD_N read_n Input 1
add_interface_port avalon_slave_0 iWR_N write_n Input 1
add_interface_port avalon_slave_0 iCS_N chipselect_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ENET_CLK export Output 1
add_interface_port conduit_end ENET_CMD export Output 1
add_interface_port conduit_end ENET_CS_N export Output 1
add_interface_port conduit_end ENET_DATA export Bidir 16
add_interface_port conduit_end ENET_INT export Input 1
add_interface_port conduit_end ENET_RD_N export Output 1
add_interface_port conduit_end ENET_RST_N export Output 1
add_interface_port conduit_end ENET_WR_N export Output 1
add_interface_port conduit_end iOSC_50 export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock_sink

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender oINT irq_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink iRST_N reset_n Input 1
# | 
# +-----------------------------------
