# TCL File Generated by Component Editor 11.1sp1
# Mon Jan 30 20:29:34 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SRAM_16Bit_512K "SRAM_16Bit_512K" v1.0
# | null 2012.01.30.20:29:34
# | 
# | 
# | D:/Home/User/Desktop/SOPC_Builder/Reference_Design/DE2_qsys/SRAM_16Bit_512K/hdl/SRAM_16Bit_512K.v
# | 
# |    ./SRAM_16Bit_512K.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module SRAM_16Bit_512K
# | 
set_module_property NAME SRAM_16Bit_512K
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME SRAM_16Bit_512K
set_module_property TOP_LEVEL_HDL_FILE SRAM_16Bit_512K.v
set_module_property TOP_LEVEL_HDL_MODULE SRAM_16Bit_512K
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME SRAM_16Bit_512K
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SRAM_16Bit_512K.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 524288
set_interface_property avalon_slave_0 holdTime 20
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 20
set_interface_property avalon_slave_0 readWaitTime 20
set_interface_property avalon_slave_0 setupTime 20
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitStates 20
set_interface_property avalon_slave_0 writeWaitTime 20

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iADDR address Input 18
add_interface_port avalon_slave_0 iWE_N write_n Input 1
add_interface_port avalon_slave_0 iOE_N read_n Input 1
add_interface_port avalon_slave_0 iCE_N chipselect_n Input 1
add_interface_port avalon_slave_0 iBE_N byteenable_n Input 2
add_interface_port avalon_slave_0 oDATA readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end SRAM_WE_N export Output 1
add_interface_port conduit_end SRAM_UB_N export Output 1
add_interface_port conduit_end SRAM_OE_N export Output 1
add_interface_port conduit_end SRAM_LB_N export Output 1
add_interface_port conduit_end SRAM_DQ export Bidir 16
add_interface_port conduit_end SRAM_CE_N export Output 1
add_interface_port conduit_end SRAM_ADDR export Output 18
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink iRST_N reset_n Input 1
# | 
# +-----------------------------------
