# TCL File Generated by Component Editor 11.1sp1
# Tue Jan 31 11:35:57 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | VGA_NIOS_CTRL "VGA_NIOS_CTRL" v1.0
# | null 2012.01.31.11:35:57
# | 
# | 
# | D:/Home/User/Desktop/SOPC_Builder/Reference_Design/DE2_qsys/Binary_VGA_Controller/hdl/VGA_NIOS_CTRL.v
# | 
# |    ./Img_DATA.hex 
# |    ./Img_RAM.v syn, sim
# |    ./VGA_Controller.v syn, sim
# |    ./VGA_NIOS_CTRL.v syn, sim
# |    ./VGA_OSD_RAM.v syn, sim
# |    ./VGA_Param.h 
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module VGA_NIOS_CTRL
# | 
set_module_property NAME VGA_NIOS_CTRL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME VGA_NIOS_CTRL
set_module_property TOP_LEVEL_HDL_FILE VGA_NIOS_CTRL.v
set_module_property TOP_LEVEL_HDL_MODULE VGA_NIOS_CTRL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME VGA_NIOS_CTRL
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Img_DATA.hex ""
add_file Img_RAM.v {SYNTHESIS SIMULATION}
add_file VGA_Controller.v {SYNTHESIS SIMULATION}
add_file VGA_NIOS_CTRL.v {SYNTHESIS SIMULATION}
add_file VGA_OSD_RAM.v {SYNTHESIS SIMULATION}
add_file VGA_Param.h ""
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter RAM_SIZE STD_LOGIC_VECTOR 307200
set_parameter_property RAM_SIZE DEFAULT_VALUE 307200
set_parameter_property RAM_SIZE DISPLAY_NAME RAM_SIZE
set_parameter_property RAM_SIZE WIDTH 21
set_parameter_property RAM_SIZE TYPE STD_LOGIC_VECTOR
set_parameter_property RAM_SIZE UNITS None
set_parameter_property RAM_SIZE ALLOWED_RANGES 0:2097151
set_parameter_property RAM_SIZE AFFECTS_GENERATION false
set_parameter_property RAM_SIZE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 524288
set_interface_property avalon_slave_0 holdTime 1
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 1
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iADDR address Input 19
add_interface_port avalon_slave_0 iWR write Input 1
add_interface_port avalon_slave_0 iRD read Input 1
add_interface_port avalon_slave_0 iCS chipselect Input 1
add_interface_port avalon_slave_0 oDATA readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end iCLK_25 export Input 1
add_interface_port conduit_end VGA_B export Output 10
add_interface_port conduit_end VGA_BLANK export Output 1
add_interface_port conduit_end VGA_CLK export Output 1
add_interface_port conduit_end VGA_G export Output 10
add_interface_port conduit_end VGA_HS export Output 1
add_interface_port conduit_end VGA_R export Output 10
add_interface_port conduit_end VGA_SYNC export Output 1
add_interface_port conduit_end VGA_VS export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink iRST_N reset Input 1
# | 
# +-----------------------------------
